#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Iinclude
CFLAGS = -Wall `wx-config --cflags`
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = `wx-config --libs`

INC_DEBUG = $(INC) -Iinclude -IUNFuzzy-3/include
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/UNFuzzyNetwork

INC_RELEASE = $(INC) -Iinclude -IUNFuzzy-3/include
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  -s $(LDFLAGS)
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/UNFuzzyNetwork

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/DialogoCalculoRed.o $(OBJDIR_DEBUG)/src/DialogoMotor.o $(OBJDIR_DEBUG)/src/DialogoInfo.o $(OBJDIR_DEBUG)/src/DialogoFuncionSld.o $(OBJDIR_DEBUG)/src/DialogoFuncionRed.o $(OBJDIR_DEBUG)/src/DialogoFuncion.o $(OBJDIR_DEBUG)/src/DialogoEntrenamiento.o $(OBJDIR_DEBUG)/src/DialogoEditarVariable.o $(OBJDIR_DEBUG)/src/DialogoDifusor.o $(OBJDIR_DEBUG)/src/DialogoCalculoSld.o $(OBJDIR_DEBUG)/src/DialogoPaso.o $(OBJDIR_DEBUG)/src/DialogoCalculo.o $(OBJDIR_DEBUG)/src/DialogoAutodefinirVariable.o $(OBJDIR_DEBUG)/src/ConjuntoDifuso.o $(OBJDIR_DEBUG)/src/Concresor.o $(OBJDIR_DEBUG)/src/BloqueConcrecion.o $(OBJDIR_DEBUG)/src/Arreglo.o $(OBJDIR_DEBUG)/src/Archivador.o $(OBJDIR_DEBUG)/src/Regla.o $(OBJDIR_DEBUG)/src/red.o $(OBJDIR_DEBUG)/src/pin.o $(OBJDIR_DEBUG)/src/nodo.o $(OBJDIR_DEBUG)/src/graficadorRed.o $(OBJDIR_DEBUG)/src/capa.o $(OBJDIR_DEBUG)/src/archivadorRed.o $(OBJDIR_DEBUG)/src/Variable.o $(OBJDIR_DEBUG)/src/Universo.o $(OBJDIR_DEBUG)/src/SistemaLogicaDifusa.o $(OBJDIR_DEBUG)/src/Norma.o $(OBJDIR_DEBUG)/src/MaquinaInferencia.o $(OBJDIR_DEBUG)/src/Implicacion.o $(OBJDIR_DEBUG)/src/Graficador.o $(OBJDIR_DEBUG)/src/Difusor.o $(OBJDIR_DEBUG)/src/DialogoVariable.o $(OBJDIR_DEBUG)/src/DialogoSLD.o $(OBJDIR_DEBUG)/src/DialogoReglas.o $(OBJDIR_DEBUG)/UNFuzzyNetworkMain.o $(OBJDIR_DEBUG)/UNFuzzyNetworkApp.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/DialogoCalculoRed.o $(OBJDIR_RELEASE)/src/DialogoMotor.o $(OBJDIR_RELEASE)/src/DialogoInfo.o $(OBJDIR_RELEASE)/src/DialogoFuncionSld.o $(OBJDIR_RELEASE)/src/DialogoFuncionRed.o $(OBJDIR_RELEASE)/src/DialogoFuncion.o $(OBJDIR_RELEASE)/src/DialogoEntrenamiento.o $(OBJDIR_RELEASE)/src/DialogoEditarVariable.o $(OBJDIR_RELEASE)/src/DialogoDifusor.o $(OBJDIR_RELEASE)/src/DialogoCalculoSld.o $(OBJDIR_RELEASE)/src/DialogoPaso.o $(OBJDIR_RELEASE)/src/DialogoCalculo.o $(OBJDIR_RELEASE)/src/DialogoAutodefinirVariable.o $(OBJDIR_RELEASE)/src/ConjuntoDifuso.o $(OBJDIR_RELEASE)/src/Concresor.o $(OBJDIR_RELEASE)/src/BloqueConcrecion.o $(OBJDIR_RELEASE)/src/Arreglo.o $(OBJDIR_RELEASE)/src/Archivador.o $(OBJDIR_RELEASE)/src/Regla.o $(OBJDIR_RELEASE)/src/red.o $(OBJDIR_RELEASE)/src/pin.o $(OBJDIR_RELEASE)/src/nodo.o $(OBJDIR_RELEASE)/src/graficadorRed.o $(OBJDIR_RELEASE)/src/capa.o $(OBJDIR_RELEASE)/src/archivadorRed.o $(OBJDIR_RELEASE)/src/Variable.o $(OBJDIR_RELEASE)/src/Universo.o $(OBJDIR_RELEASE)/src/SistemaLogicaDifusa.o $(OBJDIR_RELEASE)/src/Norma.o $(OBJDIR_RELEASE)/src/MaquinaInferencia.o $(OBJDIR_RELEASE)/src/Implicacion.o $(OBJDIR_RELEASE)/src/Graficador.o $(OBJDIR_RELEASE)/src/Difusor.o $(OBJDIR_RELEASE)/src/DialogoVariable.o $(OBJDIR_RELEASE)/src/DialogoSLD.o $(OBJDIR_RELEASE)/src/DialogoReglas.o $(OBJDIR_RELEASE)/UNFuzzyNetworkMain.o $(OBJDIR_RELEASE)/UNFuzzyNetworkApp.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/DialogoCalculoRed.o: src/DialogoCalculoRed.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoCalculoRed.cpp -o $(OBJDIR_DEBUG)/src/DialogoCalculoRed.o

$(OBJDIR_DEBUG)/src/DialogoMotor.o: src/DialogoMotor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoMotor.cpp -o $(OBJDIR_DEBUG)/src/DialogoMotor.o

$(OBJDIR_DEBUG)/src/DialogoInfo.o: src/DialogoInfo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoInfo.cpp -o $(OBJDIR_DEBUG)/src/DialogoInfo.o

$(OBJDIR_DEBUG)/src/DialogoFuncionSld.o: src/DialogoFuncionSld.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoFuncionSld.cpp -o $(OBJDIR_DEBUG)/src/DialogoFuncionSld.o

$(OBJDIR_DEBUG)/src/DialogoFuncionRed.o: src/DialogoFuncionRed.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoFuncionRed.cpp -o $(OBJDIR_DEBUG)/src/DialogoFuncionRed.o

$(OBJDIR_DEBUG)/src/DialogoFuncion.o: src/DialogoFuncion.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoFuncion.cpp -o $(OBJDIR_DEBUG)/src/DialogoFuncion.o

$(OBJDIR_DEBUG)/src/DialogoEntrenamiento.o: src/DialogoEntrenamiento.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoEntrenamiento.cpp -o $(OBJDIR_DEBUG)/src/DialogoEntrenamiento.o

$(OBJDIR_DEBUG)/src/DialogoEditarVariable.o: src/DialogoEditarVariable.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoEditarVariable.cpp -o $(OBJDIR_DEBUG)/src/DialogoEditarVariable.o

$(OBJDIR_DEBUG)/src/DialogoDifusor.o: src/DialogoDifusor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoDifusor.cpp -o $(OBJDIR_DEBUG)/src/DialogoDifusor.o

$(OBJDIR_DEBUG)/src/DialogoCalculoSld.o: src/DialogoCalculoSld.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoCalculoSld.cpp -o $(OBJDIR_DEBUG)/src/DialogoCalculoSld.o

$(OBJDIR_DEBUG)/src/DialogoPaso.o: src/DialogoPaso.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoPaso.cpp -o $(OBJDIR_DEBUG)/src/DialogoPaso.o

$(OBJDIR_DEBUG)/src/DialogoCalculo.o: src/DialogoCalculo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoCalculo.cpp -o $(OBJDIR_DEBUG)/src/DialogoCalculo.o

$(OBJDIR_DEBUG)/src/DialogoAutodefinirVariable.o: src/DialogoAutodefinirVariable.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoAutodefinirVariable.cpp -o $(OBJDIR_DEBUG)/src/DialogoAutodefinirVariable.o

$(OBJDIR_DEBUG)/src/ConjuntoDifuso.o: src/ConjuntoDifuso.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/ConjuntoDifuso.cpp -o $(OBJDIR_DEBUG)/src/ConjuntoDifuso.o

$(OBJDIR_DEBUG)/src/Concresor.o: src/Concresor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Concresor.cpp -o $(OBJDIR_DEBUG)/src/Concresor.o

$(OBJDIR_DEBUG)/src/BloqueConcrecion.o: src/BloqueConcrecion.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/BloqueConcrecion.cpp -o $(OBJDIR_DEBUG)/src/BloqueConcrecion.o

$(OBJDIR_DEBUG)/src/Arreglo.o: src/Arreglo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Arreglo.cpp -o $(OBJDIR_DEBUG)/src/Arreglo.o

$(OBJDIR_DEBUG)/src/Archivador.o: src/Archivador.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Archivador.cpp -o $(OBJDIR_DEBUG)/src/Archivador.o

$(OBJDIR_DEBUG)/src/Regla.o: src/Regla.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Regla.cpp -o $(OBJDIR_DEBUG)/src/Regla.o

$(OBJDIR_DEBUG)/src/red.o: src/red.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/red.cpp -o $(OBJDIR_DEBUG)/src/red.o

$(OBJDIR_DEBUG)/src/pin.o: src/pin.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/pin.cpp -o $(OBJDIR_DEBUG)/src/pin.o

$(OBJDIR_DEBUG)/src/nodo.o: src/nodo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/nodo.cpp -o $(OBJDIR_DEBUG)/src/nodo.o

$(OBJDIR_DEBUG)/src/graficadorRed.o: src/graficadorRed.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/graficadorRed.cpp -o $(OBJDIR_DEBUG)/src/graficadorRed.o

$(OBJDIR_DEBUG)/src/capa.o: src/capa.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/capa.cpp -o $(OBJDIR_DEBUG)/src/capa.o

$(OBJDIR_DEBUG)/src/archivadorRed.o: src/archivadorRed.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/archivadorRed.cpp -o $(OBJDIR_DEBUG)/src/archivadorRed.o

$(OBJDIR_DEBUG)/src/Variable.o: src/Variable.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Variable.cpp -o $(OBJDIR_DEBUG)/src/Variable.o

$(OBJDIR_DEBUG)/src/Universo.o: src/Universo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Universo.cpp -o $(OBJDIR_DEBUG)/src/Universo.o

$(OBJDIR_DEBUG)/src/SistemaLogicaDifusa.o: src/SistemaLogicaDifusa.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/SistemaLogicaDifusa.cpp -o $(OBJDIR_DEBUG)/src/SistemaLogicaDifusa.o

$(OBJDIR_DEBUG)/src/Norma.o: src/Norma.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Norma.cpp -o $(OBJDIR_DEBUG)/src/Norma.o

$(OBJDIR_DEBUG)/src/MaquinaInferencia.o: src/MaquinaInferencia.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/MaquinaInferencia.cpp -o $(OBJDIR_DEBUG)/src/MaquinaInferencia.o

$(OBJDIR_DEBUG)/src/Implicacion.o: src/Implicacion.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Implicacion.cpp -o $(OBJDIR_DEBUG)/src/Implicacion.o

$(OBJDIR_DEBUG)/src/Graficador.o: src/Graficador.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Graficador.cpp -o $(OBJDIR_DEBUG)/src/Graficador.o

$(OBJDIR_DEBUG)/src/Difusor.o: src/Difusor.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Difusor.cpp -o $(OBJDIR_DEBUG)/src/Difusor.o

$(OBJDIR_DEBUG)/src/DialogoVariable.o: src/DialogoVariable.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoVariable.cpp -o $(OBJDIR_DEBUG)/src/DialogoVariable.o

$(OBJDIR_DEBUG)/src/DialogoSLD.o: src/DialogoSLD.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoSLD.cpp -o $(OBJDIR_DEBUG)/src/DialogoSLD.o

$(OBJDIR_DEBUG)/src/DialogoReglas.o: src/DialogoReglas.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/DialogoReglas.cpp -o $(OBJDIR_DEBUG)/src/DialogoReglas.o

$(OBJDIR_DEBUG)/UNFuzzyNetworkMain.o: UNFuzzyNetworkMain.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c UNFuzzyNetworkMain.cpp -o $(OBJDIR_DEBUG)/UNFuzzyNetworkMain.o

$(OBJDIR_DEBUG)/UNFuzzyNetworkApp.o: UNFuzzyNetworkApp.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c UNFuzzyNetworkApp.cpp -o $(OBJDIR_DEBUG)/UNFuzzyNetworkApp.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/DialogoCalculoRed.o: src/DialogoCalculoRed.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoCalculoRed.cpp -o $(OBJDIR_RELEASE)/src/DialogoCalculoRed.o

$(OBJDIR_RELEASE)/src/DialogoMotor.o: src/DialogoMotor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoMotor.cpp -o $(OBJDIR_RELEASE)/src/DialogoMotor.o

$(OBJDIR_RELEASE)/src/DialogoInfo.o: src/DialogoInfo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoInfo.cpp -o $(OBJDIR_RELEASE)/src/DialogoInfo.o

$(OBJDIR_RELEASE)/src/DialogoFuncionSld.o: src/DialogoFuncionSld.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoFuncionSld.cpp -o $(OBJDIR_RELEASE)/src/DialogoFuncionSld.o

$(OBJDIR_RELEASE)/src/DialogoFuncionRed.o: src/DialogoFuncionRed.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoFuncionRed.cpp -o $(OBJDIR_RELEASE)/src/DialogoFuncionRed.o

$(OBJDIR_RELEASE)/src/DialogoFuncion.o: src/DialogoFuncion.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoFuncion.cpp -o $(OBJDIR_RELEASE)/src/DialogoFuncion.o

$(OBJDIR_RELEASE)/src/DialogoEntrenamiento.o: src/DialogoEntrenamiento.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoEntrenamiento.cpp -o $(OBJDIR_RELEASE)/src/DialogoEntrenamiento.o

$(OBJDIR_RELEASE)/src/DialogoEditarVariable.o: src/DialogoEditarVariable.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoEditarVariable.cpp -o $(OBJDIR_RELEASE)/src/DialogoEditarVariable.o

$(OBJDIR_RELEASE)/src/DialogoDifusor.o: src/DialogoDifusor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoDifusor.cpp -o $(OBJDIR_RELEASE)/src/DialogoDifusor.o

$(OBJDIR_RELEASE)/src/DialogoCalculoSld.o: src/DialogoCalculoSld.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoCalculoSld.cpp -o $(OBJDIR_RELEASE)/src/DialogoCalculoSld.o

$(OBJDIR_RELEASE)/src/DialogoPaso.o: src/DialogoPaso.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoPaso.cpp -o $(OBJDIR_RELEASE)/src/DialogoPaso.o

$(OBJDIR_RELEASE)/src/DialogoCalculo.o: src/DialogoCalculo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoCalculo.cpp -o $(OBJDIR_RELEASE)/src/DialogoCalculo.o

$(OBJDIR_RELEASE)/src/DialogoAutodefinirVariable.o: src/DialogoAutodefinirVariable.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoAutodefinirVariable.cpp -o $(OBJDIR_RELEASE)/src/DialogoAutodefinirVariable.o

$(OBJDIR_RELEASE)/src/ConjuntoDifuso.o: src/ConjuntoDifuso.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/ConjuntoDifuso.cpp -o $(OBJDIR_RELEASE)/src/ConjuntoDifuso.o

$(OBJDIR_RELEASE)/src/Concresor.o: src/Concresor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Concresor.cpp -o $(OBJDIR_RELEASE)/src/Concresor.o

$(OBJDIR_RELEASE)/src/BloqueConcrecion.o: src/BloqueConcrecion.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/BloqueConcrecion.cpp -o $(OBJDIR_RELEASE)/src/BloqueConcrecion.o

$(OBJDIR_RELEASE)/src/Arreglo.o: src/Arreglo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Arreglo.cpp -o $(OBJDIR_RELEASE)/src/Arreglo.o

$(OBJDIR_RELEASE)/src/Archivador.o: src/Archivador.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Archivador.cpp -o $(OBJDIR_RELEASE)/src/Archivador.o

$(OBJDIR_RELEASE)/src/Regla.o: src/Regla.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Regla.cpp -o $(OBJDIR_RELEASE)/src/Regla.o

$(OBJDIR_RELEASE)/src/red.o: src/red.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/red.cpp -o $(OBJDIR_RELEASE)/src/red.o

$(OBJDIR_RELEASE)/src/pin.o: src/pin.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/pin.cpp -o $(OBJDIR_RELEASE)/src/pin.o

$(OBJDIR_RELEASE)/src/nodo.o: src/nodo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/nodo.cpp -o $(OBJDIR_RELEASE)/src/nodo.o

$(OBJDIR_RELEASE)/src/graficadorRed.o: src/graficadorRed.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/graficadorRed.cpp -o $(OBJDIR_RELEASE)/src/graficadorRed.o

$(OBJDIR_RELEASE)/src/capa.o: src/capa.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/capa.cpp -o $(OBJDIR_RELEASE)/src/capa.o

$(OBJDIR_RELEASE)/src/archivadorRed.o: src/archivadorRed.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/archivadorRed.cpp -o $(OBJDIR_RELEASE)/src/archivadorRed.o

$(OBJDIR_RELEASE)/src/Variable.o: src/Variable.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Variable.cpp -o $(OBJDIR_RELEASE)/src/Variable.o

$(OBJDIR_RELEASE)/src/Universo.o: src/Universo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Universo.cpp -o $(OBJDIR_RELEASE)/src/Universo.o

$(OBJDIR_RELEASE)/src/SistemaLogicaDifusa.o: src/SistemaLogicaDifusa.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/SistemaLogicaDifusa.cpp -o $(OBJDIR_RELEASE)/src/SistemaLogicaDifusa.o

$(OBJDIR_RELEASE)/src/Norma.o: src/Norma.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Norma.cpp -o $(OBJDIR_RELEASE)/src/Norma.o

$(OBJDIR_RELEASE)/src/MaquinaInferencia.o: src/MaquinaInferencia.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/MaquinaInferencia.cpp -o $(OBJDIR_RELEASE)/src/MaquinaInferencia.o

$(OBJDIR_RELEASE)/src/Implicacion.o: src/Implicacion.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Implicacion.cpp -o $(OBJDIR_RELEASE)/src/Implicacion.o

$(OBJDIR_RELEASE)/src/Graficador.o: src/Graficador.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Graficador.cpp -o $(OBJDIR_RELEASE)/src/Graficador.o

$(OBJDIR_RELEASE)/src/Difusor.o: src/Difusor.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Difusor.cpp -o $(OBJDIR_RELEASE)/src/Difusor.o

$(OBJDIR_RELEASE)/src/DialogoVariable.o: src/DialogoVariable.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoVariable.cpp -o $(OBJDIR_RELEASE)/src/DialogoVariable.o

$(OBJDIR_RELEASE)/src/DialogoSLD.o: src/DialogoSLD.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoSLD.cpp -o $(OBJDIR_RELEASE)/src/DialogoSLD.o

$(OBJDIR_RELEASE)/src/DialogoReglas.o: src/DialogoReglas.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/DialogoReglas.cpp -o $(OBJDIR_RELEASE)/src/DialogoReglas.o

$(OBJDIR_RELEASE)/UNFuzzyNetworkMain.o: UNFuzzyNetworkMain.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c UNFuzzyNetworkMain.cpp -o $(OBJDIR_RELEASE)/UNFuzzyNetworkMain.o

$(OBJDIR_RELEASE)/UNFuzzyNetworkApp.o: UNFuzzyNetworkApp.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c UNFuzzyNetworkApp.cpp -o $(OBJDIR_RELEASE)/UNFuzzyNetworkApp.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

